### ISSUE TITLE
XSD Choice Conversion To Avro

### ISSUE THREAD

**Issue by TheBerryBeast** [roycem90/xml-avro#10]
The XSD choice element does not seem to be converting properly to avro.  In my mind the choice element should be converted to a type union but is instead converted to a union of fields.  Instead of one of many fields required it currently requires all fields to be present.  

 <xsd:choice>
            <xsd:element name="option1" type="xsd:string"/>
            <xsd:element name="option2" type="xsd:int"/>
            <xsd:element name="option3" type="xsd:double"/>
            <xsd:element name="option4" type="xsd:boolean"/>
</xsd:choice>

**Current:**

 "name" : "data",
                  "type" : {
                    "type" : "record",
                    "name" : "DataSourceType",
                    "fields" : [ {
                      "name" : "option1",
                      "type" : [ "null", "string" ],
                      "default" : null,
                      "source" : "element :option1"
                    }, {
                      "name" : "option2",
                      "type" : [ "null", "int" ],
                      "default" : null,
                      "source" : "element:option2"
                    }, {
                      "name" : "option3",
                      "type" : [ "null", "double" ],
                      "default" : null,
                      "source" : "element :option3"
                    }, {
                      "name" : "option4",
                      "type" : [ "null", "boolean" ],
                      "default" : null,
                      "source" : "element :option4"
                    } ]
                  }

**Proposed:**
"type" :["string", "int", "double", "boolean"]

**Comment by GeethanadhP** [comment]
that would lose the name information
as in you wouldn't know if the data is assigned to 'option1' or 'option2' or ...

**Comment by TheBerryBeast** [comment]
I agree, but this would at least implement some of the functionality of the choice element as opposed to completely disregarding it.  Maybe a cmd option?

**Comment by GeethanadhP** [comment]
i think it would take quite a time, as it would require a changes in both avro and avsc generator,
unfortunately i am busy with some stuff and would not like to spend much time unless its a required bug

so if you have coding knowledge and are interested you can make the change and put a pull request
if not u have to live with the current changes.. 

sorry about it dude, but i will try to make changes when i have sometime
