### ISSUE TITLE
"no main manifest attribute" error

### ISSUE THREAD

**Issue by haritrichy** [roycem90/xml-avro#2]
Could anyone please help me here? I tried the following commands to test the converter but no luck. Is there an example post I can find somewhere?

Command: java -jar ./libs/xml-avro-1.7.4.jar -b ./resources/test/ -xsd books.xsd books_new.avsc
Output: **no main manifest attribute, in ./libs/xml-avro-1.7.4.jar**

java -jar ./libs/xml-avro-all-1.7.4.jar -b ./resources/test/ -xsd books.xsd books_new.avsc
Output: **No result and books_new.avsc not created**

**Comment by GeethanadhP** [comment]
did you try using java -jar ./libs/xml-avro-all-1.7.4.jar instead

**Comment by haritrichy** [comment]
Yes. I did try both the jar files. *all*.jar doesn't return any result. Not sure if I'm doing anything wrong. I look forward for a sample post. Thanks for your help

java -jar ./libs/xml-avro-all-1.7.4.jar -b ./resources/test/ -xsd books.xsd books_new.avsc
Output: **No result and books_new.avsc not created**

**Comment by GeethanadhP** [comment]
hey sorry, i hope i am very late on the reply here

but did you manage to get the avsc??
if not are you getting any error message or something??

**Comment by veeravn** [comment]
Hi I am also facing the same issue of running the all-1.7.8 jar file and not getting anything back.  I am not getting any error message either.

**Comment by veeravn** [comment]
I used the --toAvsc option with the xml-avro-all-1.7.8 jar file instead of the -xsd option and I was able to generate the file.  I checked the file and it seems correct.  This is the command I used: 
java -jar xml-avro-all-1.7.8.jar --baseDir . --toAvsc "xsdFileName"
