### ISSUE TITLE
Have to manually define attributes once avsc is created - need help

### ISSUE THREAD

**Issue by jkckiran** [roycem90/xml-avro#20]
This library is recognising elements and attributes in the same manner. Need to be differentiated.
For example the XSD contains :
```
<Student Index="1">
        <Surname>Aaron</Surname>
 </Student>
```
And the corresponding avsc contents are : 
```
{
    "name" : "Student",
    "type" : [ "null", {
      "type" : "record",
      "name" : "rspStudent",
      "fields" : [ {
        "name" : "Surname",
        "type" : [ "null", "string" ],
        "default" : null,
        "source" : "element Surname"
      }, {
        "name" : "Index",
        "type" : "string",
        "source" : "attribute Index"
      } ]
```
Now I am modifying all the attributes and inserting an "_" before it's name to differentiate from elements.
Any way to resolve this ?

**Comment by GeethanadhP** [comment]
just added the option 

below option under XSD config, check ReadMe.md, also make sure to take latest code 
attributePrefix: "_"          # Optional, will assign the specified prefix for attributes in the avsc schema

**Comment by jkckiran** [comment]
Thanks @roycem90 . Will be taking the new jar for any further processing of XML
