### ISSUE TITLE
Hyphens / Dashes in XSD elements are converted to underscores in AVSC

### ISSUE THREAD

**Issue by jkckiran** [roycem90/xml-avro#24]
Hi @GeethanadhP 
We noticed that all the Hyphens / Dashes in XSD elements are converted to underscores in AVSC. 
Is this because Avro / Avsc doesn't support hyphens in the field names or any other specific reason ?

**Comment by GeethanadhP** [comment]
thats the only reason, most of the changes are based on support in avro & hive

**Comment by jkckiran** [comment]
Expected.
Since it is getting converted as underscores what is happening is in XML the element has hyphen and in avsc it is having underscore. So the Spark SQL is not able to recognize the element and hence adding "null" value to those elements even though there are proper valid values in those elements.

**Comment by GeethanadhP** [comment]
it has nothing to do with spark, xml to avro conversion should take care of that, are you sure you are getting null?, can you ping your sample xml/avsc here?

**Comment by jkckiran** [comment]
Ya xml to avro conversion will take care but as per our requirements we are not converting the xml to avro. Only the xsd is converted to avsc. That's the issue here :(

**Comment by GeethanadhP** [comment]
what are you doing with avsc without avro file?

**Comment by jkckiran** [comment]
For schema evolution we are using avsc instead of xsd. But we are using XML as-is. I know it doesn't make sense. But it's the standard pattern they are following here unfortunately

**Comment by jkckiran** [comment]
As this is nothing to do with your tool I will close this issue. Thanks for your inputs anyways
