### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by zhenik** [roycem90/xml-avro#8]
Hi, is it possible to update dependencies ? Such as : org.apache.avro, etc . . .

**Comment by GeethanadhP** [comment]
you can update them in the build.gradle file, but i don't think we can bump the major version of avro due to incompatibility issue 

what are you trying to achieve?

**Comment by zhenik** [comment]
Np, I though it design for backward compatibility, I can do it in fork. I will close this issue.

**Comment by GeethanadhP** [comment]
let me know if you manage to get it working after bumping the version :)
