### ISSUE TITLE
Questions for substitution

### ISSUE THREAD

**Issue by dan-choe** [roycem90/xml-avro#9]
If xml/xsd has element as below:
<element name="unadjustedDate" type="IdentifiedDate"/>

It prints out schema like below:

{
                        "name" : "unadjustedDate",
                        "type" : [ "null", {
                          "type" : "array",
                          "items" : "IdentifiedDate"
                        }

I want to put "IdentifiedDate"'s schemas into "items" instead of type name only.

I have tried to customize this for 3 days, but I couldn't.
Could you please share how to do it?

**Comment by GeethanadhP** [comment]
hey @dan-choe i think u may have missed something in there

If xml/xsd has element as below:
<YOUR_EXAMPLE_MISSING_HERE>

**Comment by dan-choe** [comment]
Oh!!! I just found out how to solve this issue. 
Thank you.
